#!/bin/sh
# jcz 2001-10-22

# variables
# renaming old logfiles with the yearmonthdaysecond of this script being run
alogdater=$(date +%Y%m%d%S)_alogbak
elogdater=$(date +%Y%m%d%S)_elogbak
statput=$/var/www/html/stats


# creating name for the log backup uing yearmonthdatesecond of this script being run
datearc=/home/jcz/logs/logbackup-$(date +%Y%m%d%S).tgz

# setting some HTMl into a variable for use in the analog page footer
# htmler="<center><b><a href='http://www.northredoubt.com'>[Home]</a>&nbsp;&nbsp; 
# See stat pages generated by <a href='http://www.northredoubt.com/stats/index.html'>[Webalizer]</a>
# <a href='http://www.northredoubt.com/stats.html'>[Analog]</a></b></center></font>"

# creating file name for the file of diffed logs
diffdater=diffed-$(date +%Y%m%d%S).txt

# Started keeping the old logs on march-28-2002
# moving the log files to the recycle can
# mv /home/jcz/logs/*alog /home/jcz/logs/deleteable
# mv /home/jcz/logs/*elog /home/jcz/logs/deleteable
# mv /home/jcz/logs/diffed* /home/jcz/logs/deleteable
echo OLD LOGS *HAVE BEEN KEPT*

# renaming the old logs to elogs and alogs
mv /home/jcz/logs/error_log /home/jcz/logs/$elogdater
mv /home/jcz/logs/access_log /home/jcz/logs/$alogdater
echo PREVIOUS LOGS RENAMED FOR ARCHIVING

# copying over the new logs
cd /home/jcz/logs
cp /var/log/httpd/error_log /home/jcz/logs
cp /var/log/httpd/access_log /home/jcz/logs
echo FRESH LOGS COPIED TO /home/jcz/logs

# tarring and gzipping archives of the various log files named by the variable $datearc
tar -cZf $datearc *log
echo "LOGS in /home/jcz/logs TARRED to" $datearc


###########################################################
# processing access_log to write uniqness to statfoot.txt
mv newips oldips
echo "MOVED NEWIPS TO OLDIPS"
tail -n 4000 access_log | awk '{print $1}' > newips
echo "MADE NEW NEWIPS"
echo "BUILDING STATFOOT.TXT"
echo "<center><i><h3>Domains visiting since last analysis 
(requests)</h3></i></center><pre>" > /var/www/html/stats/statfoot.txt
uniq -c newips >> /var/www/html/stats/statfoot.txt
echo "</pre>" >> /var/www/html/stats/statfoot.txt
echo "<UL>" >> /var/www/html/statfoot.txt
echo "WROTE TO STATFOOT.TXT... DIFFING"
diff oldips newips > $diffdater
echo "ok, I just made" $diffdater
# awk '{count[$1]++} END{for (name in count) print "<LI> ", name, count[name]}' $diffdater >> /var/www/html/stats/statfoot.txt
# the line that kinda works# awk '{count[$1]++}END{for (name in count) 
# print "<LI> ", name, count[name]}' $diffdater >> /var/www/html/stats/statfoot.txt
# echo "</UL>" >> /var/www/html/stats/statfoot.txt
echo "<center><b><a href='http://asterionella'>[Home]</a>&nbsp;&nbsp; See stat pages generated by <a href='http://asterionella/stats/index.html'>[Webalizer]</a> <a href='http://asterionella/stats.html'>[Analog]</a></b></center></font>" >> /var/www/html/stats/statfoot.txt ##########################################################

# run & time stats for northredoubt. webalizer is being forced to skip the history file with the elaborate example
time analog -G +g/home/jcz/config/aster_analog.cfg
# /usr/local/bin/webalizer -c /home/jcz/nrd_webalizer.conf
# webalizer -d -f -i -c /home/jcz/nrd_webalizer.conf
webalizer -c /home/jcz/config/aster_webalizer.conf
