#!/bin/sh
# v1 jcz 25-jun-2002
# v2 jcz 27-Mar-2007 - edited for CORE
# v3 jcz 26-Jan-2010 - edited for websrv2

# This script will setup a new user account, create a personal web
# directory for them in their home directory and create a database for them

# todo: 
# add lines below to append virtual host and log directory information
# for apache and the new user. Do this by appending error_log and 
# virtual host entries at the bottom of the apache conf files
# 
# this script is not smart. must add
# tests for success or failure with
# an emailing option
# 


############################
# enable for debugging #####
############################
#   set -vx

# Date and other variables pretty self explanatory, S is seconds
# date format is currently YYYYMMDD_HHMMSS
        dater=$(date +%Y%m%d_%H%M%S)
        dayer=$(date +%a)
        namer=$(whoami)
        hoster=$(hostname)
        directory=$(pwd)
        wbrot="public_html" # webroot directory for apache
	httpdconf="/etc/httpd/conf/httpd.conf"
	smbconf="/etc/samba/smb.conf"

# sets day of the week for incremental backups
        set $(date)

# THE MYSQL SUPERWORD
        superword="yub.miha"

clear
echo ""
echo ""
echo "YOU HAD BETTER BE AN ADMIN. WELCOME TO NEW USER SETUP SCRIPT"
echo ""
echo "!!!!"
echo ""

echo -n "Enter NEW USERNAME: "
read namer

echo "" > $namer.install.txt
# echo "Sample passwords" >> $namer.install.txt
echo "***************************" >> $namer.install.txt
# apg -t -a0 -m8 >> $namer.install.txt
echo "" >> $namer.install.txt

echo ""
# echo "Some example passwords are: "
echo ""
# cat $namer.install.txt

echo -n "Enter USER password: "
read pword

/usr/sbin/./useradd $namer

mkdir /home/$namer/scripts
mkdir /home/$namer/bin
mkdir /home/$namer/public_html
ln -s /home/$namer/public_html /home/$namer/www

# modify to point some central source of useful scripts for users
# When these actually be placed in the scripts/ directory
# cp /home/jcz/scripts/backup.sh /home/$namer
# cp /home/jcz/bin/backup.sh /home/$namer

chown -R $namer /home/$namer
chgrp -R $namer /home/$namer

echo ""
echo "CREATING MYSQL DB"
echo "create database" $namer ";" > $namer.sql
echo "grant all privileges on" $namer".* to" $namer"@localhost identified by '"$pword"' with grant option;" >>$namer.sql
echo "grant all privileges on" $namer".* to" $namer"@\"%\" identified by '"$pword"' with grant option;" >>$namer.sql

mysql -ujcz -pyub.miha <$namer.sql
cp $namer.sql /home/$namer
cp $namer.sql /home/root

echo "<!DOCTYPE HTML PUBLIC -//W3C//DTD HTML 4.01 Transitional//EN>" > /home/$namer/$wbrot/index.html
echo "<BR>" >> /home/$namer/$wbrot/index.html
echo "<HTML><HEAD><TITLE>$namer INDEX.HTML</TITLE></HEAD>" >> /home/$namer/$wbrot/index.html
echo "<BR>" >> /home/$namer/$wbrot/index.html
echo "<BODY BGCOLOR=#CCFF99 TEXT=#000000>" >> /home/$namer/$wbrot/index.html
echo "<BR>" >> /home/$namer/$wbrot/index.html
echo "<H1>Hi $namer!!!!</H1>" >> /home/$namer/$wbrot/index.html
echo "<BR>" >> /home/$namer/$wbrot/index.html
echo "<CENTER><B><P>*** I am your home page generated by the user " >> /home/$namer/$wbrot/index.html
echo "creator script that was kindly run by" >> /home/$namer/$wbrot/index.html
echo "<A HREF=http://$hoster>$hoster</A> for you ***</P></B><HR></CENTER>" >> /home/$namer/$wbrot/index.html
echo "In case you were wondering, I am located in /home/$namer/public_html" >> /home/$namer/$wbrot/index.html
echo "Follow the link above to the page that provides instructions "  >> /home/$namer/$wbrot/index.html
echo " and tools for accessing this server" >> /home/$namer/$wbrot/index.html
echo "</BODY></HTML>" >> /home/$namer/$wbrot/index.html


mkdir /var/log/httpd/$namer
echo "" > $namer.vhost.txt
echo "### $namer.tetratech-ffx.com on $hoster ### " >> $namer.vhost.txt
echo "<VirtualHost *:80> "  >> $namer.vhost.txt
echo "DirectoryIndex index.html index.php index.htm index.shtml index.cgi "  >> $namer.vhost.txt
echo "ServerAdmin alex.ramirez@tetratech-ffx.com "  >> $namer.vhost.txt
echo "DocumentRoot /home/$namer/public_html "  >> $namer.vhost.txt
echo "ServerName $namer.tetratech-ffx.com "  >> $namer.vhost.txt
echo "ErrorLog /var/log/httpd/$namer/error_log "  >> $namer.vhost.txt
echo "CustomLog /var/log/httpd/$namer/access_log combined "  >> $namer.vhost.txt
echo "HostNameLookups off" >> $namer.vhost.txt
echo "php_flag display_errors on" >> $namer.vhost.txt
echo "php_value error_reporting 614" >> $namer.vhost.txt
echo "</VirtualHost> "  >> $namer.vhost.txt
echo "########################################## "  >> $namer.vhost.txt
echo ""  >> $namer.vhost.txt

cat $namer.vhost.txt >> $httpdconf
echo "Your Apache virtual host configurations -- as found in $namer.vhost.txt" >> $namer.install.txt
cat $namer.vhost.txt >> $namer.install.txt

# echo "" > $namer.smb.txt
# echo "[public_html] " >> $namer.smb.txt
# echo "       path = /home/$namer/public_html " >> $namer.smb.txt
# echo "       writeable = yes " >> $namer.smb.txt
# echo "       browseable = yes " >> $namer.smb.txt
# echo "       valid users = $namer " >> $namer.smb.txt

# cat $namer.smb.txt >> $smbconf
# echo "Your Samba configurations -- as found in $namer.smb.txt" >> $namer.install.txt
# cat $namer.smb.txt >> $namer.install.txt


echo ""
echo "You now have the directories: " >> $namer.install.txt
echo "" >> $namer.install.txt

echo "" >> $namer.install.txt
echo "www -- as symbolic link to public_html, scripts, bin, public_html ">> $namer.install.txt
echo "www/html/images, downloads, data, configs" >> $namer.install.txt
echo "A webpage has also been enabled at http://$HOSTNAME/~$namer/ " >> $namer.install.txt

echo ""
echo "* Checking the syntax of the new apache config file "
/usr/sbin/httpd -t

echo ""
echo "--- YOU MUST RESTART APACHE TO ENABLE THE VIRTUAL HOST ---"
echo " /usr/sbin/apachectl stop "
echo " /usr/sbin/apachectl start "
echo ""
echo ""
echo ""

echo "" >> $namer.install.txt
echo "appearing in your home directory" >> $namer.install.txt
echo ""  >> $namer.install.txt
echo "" >> $namer.install.txt
echo "your mysql database name is: "$namer >> $namer.install.txt
echo "Your mysql database password is: "$pword >> $namer.install.txt

echo ""
echo " ********************************* "
echo " * Displaying $namer.install.txt "

echo ""
cat $namer.install.txt


echo ""
echo "* Copying $namer.install.txt to /home/$namer and /home/root for reference"

echo ""
cp $namer.install.txt /home/$namer
cp $namer.install.txt /home/root

echo "* Changing ownership and permissions on new $namer home directories"
chmod -R 755 /home/$namer
chmod -R 754 /home/$namer/scripts
chown -R $namer:$namer /home/$namer

echo ""
echo ""
echo " SKIPPING Applying rights to the user web directory to allow apache to execute within it"
echo " Per SELinux rules "

# restorecon -R -v '/home/$namer/public_html' 

echo ""
echo ""
echo ""
echo "* THE USER " $namer " SHOULD HAVE BEEN ADDED -- NOT VERIFIED"
echo "* GOTO http://$HOSTNAME/~$namer/ TO SEE IF THEIR WEBPAGE IS SERVING CORRECTLY"
echo "* THEIR PASSWORD IS CURRENTLY NULL." 
echo "*"
echo "*"
echo "* NOW YOU MUST TYPE THE FOLLOWING AT THE COMMAND PROMPT"
echo "* TO ASSIGN THEM A PASSWORD"
echo "* passwd" $namer
echo ""
echo "* THEN PROVIDED IT THE PASSWORD " $pword
echo "* FAILURE TO ASSIGN THE SAME PASSWORD MEANS THAT THE DATABASE" 
echo "* AND USER LOGIN PASSWORD WILL NOT BE IN SYNC!!! "
echo "DONE!" 
